### ISSUE TITLE
startup example: git holo init - fs.copyFiles error

### ISSUE THREAD

**Issue by jtwiest** [JarvusInnovations/hologit#39]
When running through the quick example, the holo init step failed with the following error. I created the file manually on my own but I'm not sure what's going on with the command.

```
$ git holo init
name=holo-example
error: fs.copyFile is not a function
```

**Comment by themightychris** [comment]
@jtwiest can you report your node version? `node --version`

**Comment by jtwiest** [comment]
@themightychris 
```
$ node --version
v8.4.0
```

**Comment by themightychris** [comment]
@jtwiest yeah your node is to old, follow the official node instructions for installing current version. I gotta look into how to get npm to tell you that
