### ISSUE TITLE
instruction typo: grand tour 

### ISSUE THREAD

**Issue by jtwiest** [JarvusInnovations/hologit#40]
In the initial step for mac, the docs say git must be `>= 2.8` however the example response is only `2.17.2`. I also updated git on my machine and it tapped out at `2.22.0` so I think the docs are wrong.

**Comment by themightychris** [comment]
@jtwiest your instincts have played a trick on you! [Semantic version numbers](https://semver.org/) aren't decimals. Version `2.22` is > `2.8`
